export { NmgStore } from "./core/store.ts";
export { HashingVectorEmbedder } from "./core/vector.ts";
export { decideMemoryLoad } from "./core/gate.ts";
export type {
  HistoryRecord,
  EvidenceRole,
  DeriveMemoryInput,
  MemoryActor,
  MemoryContext,
  MemoryGateDecision,
  MemoryLoadMode,
  MemoryNode,
  MemoryNodeKind,
  MemoryRecord,
  MemoryScope,
  MemorySearchResult,
  MemoryTier,
  MemoryType,
  NodeRoute,
  NodeTransform,
  NodeRelation,
  NodeRelationType,
  RememberInput,
  RememberResult,
  SearchOptions,
  SessionArchive,
  TruthStatus,
  RebalanceResult,
  RecallCue,
  RecallIndex,
  VectorEmbedder,
} from "./core/types.ts";
