export { NmgStore } from "./core/store.ts";
export { HashingVectorEmbedder } from "./core/vector.ts";
export { OpenAIEmbeddingClient } from "./core/openai-embedding.ts";
export { UsearchAnnIndex } from "./core/ann.ts";
export { decideMemoryLoad } from "./core/gate.ts";
export type {
  ActivationSignal,
  ActiveGraph,
  ActiveGraphBudget,
  ActiveGraphBudgetUsage,
  ActiveGraphEdge,
  ConsolidationEvent,
  ConsolidationResult,
  EdgeStability,
  HistoryRecord,
  EvidenceRole,
  DeriveMemoryInput,
  MemoryActor,
  MemoryContext,
  MemoryGateDecision,
  MemoryLoadMode,
  MemoryNode,
  MemoryNodeKind,
  NodeEmbeddingDocument,
  ExternalNodeEmbedding,
  ExternalLeafEmbedding,
  LeafBlock,
  LeafEmbeddingDocument,
  MemoryRecord,
  MemoryResidence,
  MemoryScope,
  MemorySearchResult,
  MemoryTier,
  MemoryType,
  NodeRoute,
  NodeTransform,
  NodeRelation,
  NodeRelationType,
  RememberInput,
  RememberResult,
  SearchOptions,
  SessionArchive,
  TruthStatus,
  RebalanceResult,
  RecallCue,
  RecallIndex,
  VectorEmbedder,
} from "./core/types.ts";
